### ISSUE TITLE
[BUG] Player class is not working with Python 3.11.0

### ISSUE THREAD

**Issue by RavinderSingh13-git** [outside-edge/python-espncricinfo#59]
**Describe the bug**
When I am using from `espncricinfo.player import Player` and trying to execute `p = Player('277916')` its giving me an error.

**To Reproduce**
Gives me following error:
```
>>> p = Player('277916')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Singh\Desktop\Alexa Automation\.venv\Lib\site-packages\espncricinfo\player.py", line 14, in __init__
    self.player_information = self._parse_player_information()
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Singh\Desktop\Alexa Automation\.venv\Lib\site-packages\espncricinfo\player.py", line 60, in _parse_player_information
    return self.parsed_html.find_all('p', class_='ciPlayerinformationtxt')
           ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'find_all'
```

**Expected behavior**
It should give player information.

**Screenshots**

**Additional context**

**Comment by YusiferZendric** [comment]
Same error please look into it.

**Comment by YusiferZendric** [comment]
I've found a temporary solution
Remove the self.major_teams and _major_teams function or comment them out it should work

**Comment by JackMa222** [comment]
I have written a PR to attempt to fix this #62
